controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# config/routes.yaml

app_math_operation:
  path: /{operation}/{operatorA}/{operatorB}
  controller: App\Controller\MathController::operation
  methods: GET
  defaults:
        _format: 'json'

app_math_square_root:
  path: /raiz-cuadrada/{operatorA}
  controller: App\Controller\MathController::raizCuadrada
  methods: GET
  defaults:
        _format: 'json'